# Generated by Django 5.0.4 on 2024-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestlibapp', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
