# Generated by Django 5.0.4 on 2024-05-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestlibapp', '0003_libros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libros',
            new_name='libro',
        ),
    ]
